### ISSUE TITLE
azk8spull function is not supported in zsh

### ISSUE THREAD

**Issue by iffiX** [xuxinkun/littleTools#1]
Zsh and some other shells use 1 as their array start index instead of 0, therefore statements like "${array[0]}" = "docker.io" will not work.

Please consider about moving azk8spull out of the function and making it an individual script, otherwise the function will not work, even if you have written "#!/usr/bin/env bash"

**Comment by xuxinkun** [comment]
I don't know how to be compatible between zsh and bash. Maybe using `emulate bash` can solve this problem.

**Comment by iffiX** [comment]
There is no need to rewrite the script, just make azk8spull an individual script, so zsh will not source the file and treat it as an internal function. Instead bash will execute it. Eg:

`#!/usr/bin/env bash
function azk8spull()
{
	image=$1`

Change it to:
`#!/usr/bin/env bash
image=$1`

And move the script to some place like /usr/bin

**Comment by xuxinkun** [comment]
I see. I will try it later.

**Comment by xuxinkun** [comment]
`bin/azk8spull` is provided for zsh. Enjoy.
