### ISSUE TITLE
如果是sha256 的这种， 怎么处理

### ISSUE THREAD

**Issue by Mddct** [xuxinkun/littleTools#3]
比如gcr.io/kubeflow-images-public/kfam@sha256:3b0d4be7e59a3fa5ed1d80dccc832312caa94f3b2d36682524d3afc4e45164f0 ， 如何打tag

**Comment by xuxinkun** [comment]
@Mddct  没有tag的，使用digest的，可以拉取，但是无法重命名，也没法打tag。
