### ISSUE TITLE
pull完azk镜像，推荐删除

### ISSUE THREAD

**Issue by DesistDaydream** [xuxinkun/littleTools#4]
在48行下面加条这个呗~

https://github.com/xuxinkun/littleTools/blob/388ed2a36f7fa22c41bfd36adb6e03b97a15e793/azk8spull.sh#L48

`docker rmi $domainName/$repoName/$imageName`

**Comment by xuxinkun** [comment]
这个删除应该不是特别必要。因为有这个tag，也没有特别影响。如果需要，可以在你自己的脚本里自行增加。
