### ISSUE TITLE
The tool has failed?

### ISSUE THREAD

**Issue by qooke** [xuxinkun/littleTools#5]
[root@localhost ~]# azk8spull quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.24.1

## azk8spull try to pull image from mirror quay.azk8s.cn/kubernetes-ingress-controller/nginx-ingress-controller:0.24.1.
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

**Comment by xuxinkun** [comment]
自2020年开始，Proxy Server仅限于 Azure China IP 使用，不再对外提供服务。http://mirror.azk8s.cn/help/docker-registry-proxy-cache.html
