### ISSUE TITLE
azk8s pull is error

### ISSUE THREAD

**Issue by klin111** [xuxinkun/littleTools#6]
## azk8spull try to pull image from mirror gcr.azk8s.cn/google_containers/pause-amd64:3.1.
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

**Comment by xuxinkun** [comment]
自2020年开始，Proxy Server仅限于 Azure China IP 使用，不再对外提供服务。http://mirror.azk8s.cn/help/docker-registry-proxy-cache.html
